# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/device.openyurt.io_valuedescriptors.yaml
- bases/device.openyurt.io_deviceprofiles.yaml
- bases/device.openyurt.io_devices.yaml
- bases/device.openyurt.io_deviceservices.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_valuedescriptors.yaml
#- patches/webhook_in_deviceprofiles.yaml
#- patches/webhook_in_devices.yaml
#- patches/webhook_in_deviceservices.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_valuedescriptors.yaml
#- patches/cainjection_in_deviceprofiles.yaml
#- patches/cainjection_in_devices.yaml
#- patches/cainjection_in_deviceservices.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
