
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: devices.device.openyurt.io
spec:
  group: device.openyurt.io
  names:
    kind: Device
    listKind: DeviceList
    plural: devices
    shortNames:
    - dev
    singular: device
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The nodepool of device
      jsonPath: .spec.nodePool
      name: NODEPOOL
      type: string
    - description: The synced status of device
      jsonPath: .status.synced
      name: SYNCED
      type: boolean
    - description: The managed status of device
      jsonPath: .spec.managed
      name: MANAGED
      priority: 1
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Device is the Schema for the devices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DeviceSpec defines the desired state of Device
            properties:
              adminState:
                description: Admin state (locked/unlocked)
                type: string
              description:
                description: Information describing the device
                type: string
              deviceProperties:
                additionalProperties:
                  properties:
                    desiredValue:
                      type: string
                    name:
                      type: string
                    putURL:
                      type: string
                  required:
                  - desiredValue
                  - name
                  type: object
                description: TODO support the following field A list of auto-generated
                  events coming from the device AutoEvents     []AutoEvent                   `json:"autoEvents"`
                  DeviceProperties represents the expected state of the device's properties
                type: object
              labels:
                description: Other labels applied to the device to help with searching
                items:
                  type: string
                type: array
              location:
                description: Device service specific location (interface{} is an empty
                  interface so it can be anything)
                type: string
              managed:
                description: True means device is managed by cloud, cloud can update
                  the related fields False means cloud can't update the fields
                type: boolean
              nodePool:
                description: NodePool indicates which nodePool the device comes from
                type: string
              operatingState:
                description: Operating state (enabled/disabled)
                type: string
              profile:
                description: Associated Device Profile - Describes the device
                type: string
              protocols:
                additionalProperties:
                  additionalProperties:
                    type: string
                  type: object
                description: A map of supported protocols for the given device
                type: object
              service:
                description: Associated Device Service - One per device
                type: string
            required:
            - profile
            - service
            type: object
          status:
            description: DeviceStatus defines the observed state of Device
            properties:
              adminState:
                description: Admin state (locked/unlocked)
                type: string
              conditions:
                description: current device state
                items:
                  description: Condition defines an observation of a Cluster API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    severity:
                      description: Severity provides an explicit classification of
                        Reason code, so the users or machines can immediately understand
                        the current situation and act accordingly. The Severity field
                        MUST be set only when Status=False.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              deviceProperties:
                additionalProperties:
                  properties:
                    actualValue:
                      type: string
                    getURL:
                      type: string
                    name:
                      type: string
                  required:
                  - actualValue
                  - name
                  type: object
                description: it represents the actual state of the device's properties
                type: object
              edgeId:
                type: string
              lastConnected:
                description: Time (milliseconds) that the device last provided any
                  feedback or responded to any request
                format: int64
                type: integer
              lastReported:
                description: Time (milliseconds) that the device reported data to
                  the core microservice
                format: int64
                type: integer
              operatingState:
                description: Operating state (enabled/disabled)
                type: string
              synced:
                description: Synced indicates whether the device already exists on
                  both OpenYurt and edge platform
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
